Maybe we can figure out what shift the cabbies work by labeling their pickup times with a broader category tag.  This assumes a shift change at 5pm (assumptions based on IQuantNY analysis).

```{r}
taxi_indiv_shifts <- taxi_indiv %>% 
  mutate(tod = ifelse(pickup_hour>5 & pickup_hour<17, "morning_afternoon", "evening_night")) %>% 
  group_by(hack_license, tod) %>% 
  summarize(count = n()) %>% 
  spread(tod, count, fill = 0) %>% 
  mutate(morning_per_evening = morning_afternoon/evening_night)

ggplot(taxi_indiv_shifts) + geom_histogram(aes(evening_night), binwidth = 1)
ggplot(taxi_indiv_shifts) + geom_histogram(aes(morning_afternoon), binwidth = 1)
ggplot(taxi_indiv_shifts) + geom_histogram(aes(morning_per_evening), binwidth = .1) +
  xlim(0,5)
```
```{r}
tip_percentages <- taxi %>%
  select(rate_code
         , passenger_count
         , trip_time_in_secs
         , trip_distance
         , payment_type
         , fare_amount
         , surcharge
         , mta_tax
         , tolls_amount
         , total_amount
         , pickup_borough
         , tip_percentage
         ) %>% 
  filter(tip_percentage<=100)
tip_percentages <- na.omit(tip_percentages)

smp_size <- floor(0.75 * nrow(tip_percentages))
set.seed(123)
train_ind <- sample(seq_len(nrow(tip_percentages)), size = smp_size)

train <- tip_percentages[train_ind, ]
test <- tip_percentages[-train_ind, ]

rfit <- rpart(tip_percentage ~ . , data=train) 
prp(rfit)
```
